name: Deploy to GitHub Pages

on: 
  push:
    branches: main

permissions:
  contents: read  
  pages: write      
  id-token: write   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Set environment variables
        run: |
          echo "REACT_APP_TOGETHER_API_KEY=${{ secrets.REACT_APP_TOGETHER_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.REACT_APP_FIREBASE_APP_ID }}" >> $GITHUB_ENV

      - name: Build Project
        run: npm run build      

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3   
        with:
           name: 'github-pages'
           path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'